### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by thang2410199** [hippiehunter/GifRenderer#2]
I downloaded the repo, it doesn't have a sln solution file, and have only 2 project file inside windows and windows phone folder.

I tried to open the windows phone project, restore some nugget packages, but when build it gave error: 

Error 1 error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ....\packages\directxtk.2.22.13.23\build\native\directxtk.targets. C:\Users\thang2410199\Downloads\Compressed\GifRenderer-master\GifRenderer.WindowsPhone\GifRenderer.WindowsPhone.vcxproj 167 GifRenderer.WindowsPhone

I dont know what to do, and event if I manage to build successfully, still no ideal how to integrate it into my project.

I am new to how github works, it maybe a common sense for most of people but sadly not me :( Could you please help with me with this? Really love to try out. Thank you.

**Comment by hippiehunter** [comment]
I'm not sure why you're getting a nuget error, its possible you're not running the latest version of visual studio (I don't remember when they made package restore automatic). its important to note though, that you likely need to add the "shared" project to your solution as well as the phone/store project

**Comment by thang2410199** [comment]
I am running latest version of VS with latest update :( I enabled package restore option.

**Comment by LostLogic** [comment]
Depending on where you have put the GifRenderer folder (Folder with GifRenderer.Shared, .Windows and .WindowsPhone) you need to ensure you have a package dir with the extensions next to it. Also, you need the extensions in your projects pacakge folder.

IE:
VisualStudioExtensions
-GifRenderer
-- GifRenderer.Shared
-- GifRenderer.Windows
-- GifRenderer.WindowsPhone
-Packages
-- directxtk.2.22.13.23
-- LumiaImagingSDK.2.0.208

MyAwesomeProject
-MyAwesomeProject
-packages
-- directxtk.2.22.13.23
-- LumiaImagingSDK.2.0.208

Since package restore, will restore packages to your project directory, not to the project extension directory, you want to copy them from "MyAwesomeProject\packages" to the package directory "next" to the GifRenderer folder.

I really suck at explaining this, but I hope it was clear enough...

**Comment by thang2410199** [comment]
Hi, sorry it took so long for me to reply.
I just followed your instruction and get it work, big thank you!
I think this instruction should be in the ready me for everyone.
